/* Auto-generated by export_firmware.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    63
#define IDS_N_FEATURES 14
#define IDS_QMAX       127

static const int16_t ids_feature[63] = {
    2, 3, 0, 3, 3, -2, -2, 5, -2, -2, 5, 0, -2, -2, 0, -2, -2, 4, 0, 4, -2, -2, 2, -2, -2, 5, 2, -2, -2, 0, -2, -2, 0, 4, 3, 2, -2, -2, 13, -2, -2, 3, 4, -2, -2, 2, -2, -2, 4, 3, 3, -2, -2, 2, -2, -2, 4, 3, -2, -2, 2, -2, -2
};

static const int8_t ids_threshold[63] = {
    70, 80, 38, 50, 47, 0, 0, 96, 0, 0, 10, 114, 0, 0, 64, 0, 0, 79, 114, 66, 0, 0, 23, 0, 0, 125, 44, 0, 0, 51, 0, 0, 89, 65, 127, 71, 0, 0, 104, 0, 0, 110, 88, 0, 0, 71, 0, 0, 75, 121, 119, 0, 0, 92, 0, 0, 104, 123, 0, 0, 82, 0, 0
};

static const int16_t ids_left[63] = {
    1, 2, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1, 18, 19, 20, -1, -1, 23, -1, -1, 26, 27, -1, -1, 30, -1, -1, 33, 34, 35, 36, -1, -1, 39, -1, -1, 42, 43, -1, -1, 46, -1, -1, 49, 50, 51, -1, -1, 54, -1, -1, 57, 58, -1, -1, 61, -1, -1
};

static const int16_t ids_right[63] = {
    32, 17, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1, 25, 22, 21, -1, -1, 24, -1, -1, 29, 28, -1, -1, 31, -1, -1, 48, 41, 38, 37, -1, -1, 40, -1, -1, 45, 44, -1, -1, 47, -1, -1, 56, 53, 52, -1, -1, 55, -1, -1, 60, 59, -1, -1, 62, -1, -1
};

static const int8_t ids_leaf_class[63] = {
    -1, -1, -1, -1, -1, 1, 0, -1, 1, 1, -1, -1, 0, 0, -1, 1, 0, -1, -1, -1, 0, 0, -1, 0, 1, -1, -1, 0, 0, -1, 0, 1, -1, -1, -1, -1, 1, 1, -1, 1, 0, -1, -1, 0, 1, -1, 0, 1, -1, -1, -1, 1, 1, -1, 1, 0, -1, -1, 0, 1, -1, 1, 1
};

static const float ids_feat_min[14] = {
    -1.463850f, -2.236068f, -1.075029f, -1.225325f, -1.331612f, -1.264350f, -0.940238f, -346.408722f, -102.543510f, -145.706314f, -572.076782f, 0.000000f, 0.000000f, -0.802895f
};

static const float ids_feat_scale[14] = {
    0.023053f, 0.021128f, 0.041712f, 0.021731f, 0.032774f, 0.017526f, 0.042222f, 2.727650f, 5.155985f, 2.625042f, 4.504560f, 0.007874f, 0.007874f, 0.041856f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int8_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int8_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
