#!/usr/bin/env python3
"""Generate a C scaler header from a saved StandardScaler + feature names JSON."""

import argparse
import joblib, json
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS_DIR = ROOT / 'models' / 'trained_models'
FIRMWARE_DIR = ROOT / 'firmware'


def build_header_lines(names, mean, scale):
    n = len(names)
    lines = [
        '/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */',
        '#pragma once',
        '#include <stdint.h>',
        '',
        f'#define IDS_N_FEATURES {n}',
        '',
        '/* Feature index constants */',
    ]
    for i, name in enumerate(names):
        lines.append(f'#define IDS_FEAT_{name.upper():30s} {i}')

    lines += [
        '',
        '/* StandardScaler parameters (fit on training data) */',
        f'static const float ids_scaler_mean[{n}] = {{',
        '    ' + ', '.join(f'{v:.6f}f' for v in mean),
        '};',
        '',
        f'static const float ids_scaler_scale[{n}] = {{',
        '    ' + ', '.join(f'{v:.6f}f' for v in scale),
        '};',
        '',
        '/* Apply StandardScaler in-place to a raw feature vector */',
        'static inline void ids_scale_features(float *x) {',
        '    for (int i = 0; i < IDS_N_FEATURES; i++) {',
        '        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];',
        '    }',
        '}',
    ]
    return lines


def main():
    ap = argparse.ArgumentParser(description='Generate scaler header from joblib scaler')
    ap.add_argument('--dataset', choices=['nsl'], default='nsl')
    ap.add_argument('--scaler')
    ap.add_argument('--features')
    ap.add_argument('--out')
    args = ap.parse_args()

    model_dir = MODELS_DIR / f'{args.dataset}_can'
    scaler_path = Path(args.scaler) if args.scaler else model_dir / 'scaler.joblib'
    features_path = Path(args.features) if args.features else model_dir / 'features.json'
    out_path = Path(args.out) if args.out else FIRMWARE_DIR / f'{args.dataset}_can_scaler.h'

    scaler = joblib.load(scaler_path)
    with open(features_path) as f:
        names = json.load(f)

    mean  = scaler.mean_.astype(np.float32)
    scale = scaler.scale_.astype(np.float32)
    lines = build_header_lines(names, mean, scale)

    out = out_path
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines) + '\n')
    print(f'Written -> {out}')
    print(f'  {len(names)} features, mean range [{mean.min():.3f}, {mean.max():.3f}]')

if __name__ == '__main__':
    main()
