/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_FEATURES 14

/* Feature index constants */
#define IDS_FEAT_CAN_ID_NORM                    0
#define IDS_FEAT_DLC                            1
#define IDS_FEAT_DATA_MEAN                      2
#define IDS_FEAT_DATA_STD                       3
#define IDS_FEAT_DATA_ENTROPY                   4
#define IDS_FEAT_DATA_RANGE                     5
#define IDS_FEAT_HAMMING_DIST                   6
#define IDS_FEAT_INTER_ARRIVAL_MEAN             7
#define IDS_FEAT_ID_FREQ                        8
#define IDS_FEAT_BUS_LOAD                       9
#define IDS_FEAT_UNIQUE_IDS                     10
#define IDS_FEAT_DLC_ANOMALY                    11
#define IDS_FEAT_ID_IS_KNOWN                    12
#define IDS_FEAT_PAYLOAD_DELTA                  13

/* StandardScaler parameters (fit on training data) */
static const float ids_scaler_mean[14] = {
    0.376404f, 6.833333f, 35.640419f, 56.607994f, 0.959778f, 144.851700f, 10.170040f, 0.007000f, 157.443787f, 874.677612f, 5.999979f, 0.000000f, 1.000000f, 275.503204f
};

static const float ids_scaler_scale[14] = {
    0.000834f, 2.608746f, 33.152973f, 46.198360f, 0.720764f, 114.566139f, 10.816447f, 0.000020f, 1.525633f, 5.996155f, 0.008740f, 1.000000f, 1.000000f, 343.137421f
};

/* Apply StandardScaler in-place to a raw feature vector */
static inline void ids_scale_features(float *x) {
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];
    }
}
