/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_FEATURES 15

/* Feature index constants */
#define IDS_FEAT_CAN_ID_NORM                    0
#define IDS_FEAT_DLC                            1
#define IDS_FEAT_DATA_MEAN                      2
#define IDS_FEAT_DATA_STD                       3
#define IDS_FEAT_DATA_ENTROPY                   4
#define IDS_FEAT_DATA_RANGE                     5
#define IDS_FEAT_HAMMING_DIST                   6
#define IDS_FEAT_INTER_ARRIVAL_MEAN             7
#define IDS_FEAT_INTER_ARRIVAL_STD              8
#define IDS_FEAT_ID_FREQ                        9
#define IDS_FEAT_BUS_LOAD                       10
#define IDS_FEAT_UNIQUE_IDS                     11
#define IDS_FEAT_DLC_ANOMALY                    12
#define IDS_FEAT_ID_IS_KNOWN                    13
#define IDS_FEAT_PAYLOAD_DELTA                  14

/* StandardScaler parameters (fit on training data) */
static const float ids_scaler_mean[15] = {
    0.119202f, 6.027029f, 99.856064f, 80.599365f, 2.721169f, 213.658630f, 22.878040f, 0.430431f, 0.131577f, 259.551239f, 1020.503235f, 16.105062f, 0.121844f, 0.791926f, 502.573303f
};

static const float ids_scaler_scale[15] = {
    0.240964f, 2.264090f, 42.666298f, 21.529226f, 0.431139f, 45.334267f, 11.416784f, 1.345082f, 0.535033f, 206.386581f, 9.834632f, 8.949721f, 0.327105f, 0.405930f, 348.854767f
};

/* Apply StandardScaler in-place to a raw feature vector */
static inline void ids_scale_features(float *x) {
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];
    }
}
