/* Auto-generated by phase3_quantization.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    39
#define IDS_N_FEATURES 14
#define IDS_QMAX       32767

static const int16_t ids_feature[39] = {
    10, 7, 3, 0, -2, -2, 3, -2, -2, 8, 9, 7, -2, -2, -2, 3, -2, 13, -2, -2, 4, 4, -2, 1, 2, -2, -2, 5, -2, -2, 1, -2, 0, 4, -2, -2, 8, -2, -2
};

static const int16_t ids_threshold[39] = {
    5301, 3, 31002, 458, 0, 0, 31220, 0, 0, 22392, 17362, 3, 0, 0, 0, 31012, 0, 20586, 0, 0, 25468, 8490, 0, 28086, 14458, 0, 0, 16513, 0, 0, 30426, 0, 112, 31100, 0, 0, 9004, 0, 0
};

static const int16_t ids_left[39] = {
    1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, 12, -1, -1, -1, 16, -1, 18, -1, -1, 21, 22, -1, 24, 25, -1, -1, 28, -1, -1, 31, -1, 33, 34, -1, -1, 37, -1, -1
};

static const int16_t ids_right[39] = {
    20, 9, 6, 5, -1, -1, 8, -1, -1, 15, 14, 13, -1, -1, -1, 17, -1, 19, -1, -1, 30, 23, -1, 27, 26, -1, -1, 29, -1, -1, 32, -1, 36, 35, -1, -1, 38, -1, -1
};

static const int8_t ids_leaf_class[39] = {
    -1, -1, -1, -1, 0, 1, -1, 1, 0, -1, -1, -1, 0, 0, 1, -1, 0, -1, 1, 1, -1, -1, 1, -1, -1, 0, 1, -1, 0, 1, -1, 1, -1, -1, 0, 1, -1, 1, 1
};

static const float ids_feat_min[14] = {
    -0.484550f, -2.220331f, -2.337467f, -3.728357f, -5.050815f, -4.690903f, -2.003895f, -0.320003f, -1.252752f, -103.664604f, -1.687769f, -0.372491f, -1.950893f, -1.440638f
};

static const float ids_feat_scale[14] = {
    0.000126f, 0.000094f, 0.000157f, 0.000165f, 0.000174f, 0.000171f, 0.000120f, 0.000320f, 0.000148f, 0.006203f, 0.000116f, 0.000093f, 0.000075f, 0.000131f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int16_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int16_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
