/* Auto-generated by phase3_quantization.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    39
#define IDS_N_FEATURES 14
#define IDS_QMAX       /* float */

static const int16_t ids_feature[39] = {
    10, 7, 3, 0, -2, -2, 3, -2, -2, 8, 9, 7, -2, -2, -2, 3, -2, 13, -2, -2, 4, 4, -2, 1, 2, -2, -2, 5, -2, -2, 1, -2, 0, 4, -2, -2, 8, -2, -2
};

static const float ids_threshold[39] = {
    -1.073225f, -0.318903f, 1.388315f, -0.426771f, -2.000000f, -2.000000f, 1.424268f, -2.000000f, -2.000000f, 2.054989f, 4.036840f, -0.318888f, -2.000000f, -2.000000f, -2.000000f, 1.390018f, -2.000000f, 1.248160f, -2.000000f, -2.000000f, -0.622419f, -3.574558f, -2.000000f, 0.429740f, -0.071334f, -2.000000f, -2.000000f, -1.867431f, -2.000000f, -2.000000f, 0.650580f, -2.000000f, -0.470359f, 0.356801f, -2.000000f, -2.000000f, 0.077326f, -2.000000f, -2.000000f
};

static const int16_t ids_left[39] = {
    1, 2, 3, 4, -1, -1, 7, -1, -1, 10, 11, 12, -1, -1, -1, 16, -1, 18, -1, -1, 21, 22, -1, 24, 25, -1, -1, 28, -1, -1, 31, -1, 33, 34, -1, -1, 37, -1, -1
};

static const int16_t ids_right[39] = {
    20, 9, 6, 5, -1, -1, 8, -1, -1, 15, 14, 13, -1, -1, -1, 17, -1, 19, -1, -1, 30, 23, -1, 27, 26, -1, -1, 29, -1, -1, 32, -1, 36, 35, -1, -1, 38, -1, -1
};

static const int8_t ids_leaf_class[39] = {
    -1, -1, -1, -1, 0, 1, -1, 1, 0, -1, -1, -1, 0, 0, 1, -1, 0, -1, 1, 1, -1, -1, 1, -1, -1, 0, 1, -1, 0, 1, -1, 1, -1, -1, 0, 1, -1, 1, 1
};

/* Float32 inference */
static inline int ids_predict(const float *x) {
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (x[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
