/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_FEATURES 14

/* Feature index constants */
#define IDS_FEAT_CAN_ID_NORM                    0
#define IDS_FEAT_DLC                            1
#define IDS_FEAT_DATA_MEAN                      2
#define IDS_FEAT_DATA_STD                       3
#define IDS_FEAT_DATA_ENTROPY                   4
#define IDS_FEAT_DATA_RANGE                     5
#define IDS_FEAT_HAMMING_DIST                   6
#define IDS_FEAT_INTER_ARRIVAL_MEAN             7
#define IDS_FEAT_ID_FREQ                        8
#define IDS_FEAT_BUS_LOAD                       9
#define IDS_FEAT_UNIQUE_IDS                     10
#define IDS_FEAT_DLC_ANOMALY                    11
#define IDS_FEAT_ID_IS_KNOWN                    12
#define IDS_FEAT_PAYLOAD_DELTA                  13

/* StandardScaler parameters (fit on training data) */
static const float ids_scaler_mean[14] = {
    0.251099f, 6.800000f, 19.497015f, 31.086897f, 0.935238f, 85.795441f, 7.518748f, 0.006000f, 170.080139f, 850.386169f, 4.999983f, 0.000000f, 1.000000f, 139.611389f
};

static const float ids_scaler_scale[14] = {
    0.000691f, 2.400000f, 29.252424f, 37.898296f, 0.779712f, 101.315987f, 8.431400f, 0.000017f, 1.710934f, 6.260788f, 0.007071f, 1.000000f, 1.000000f, 234.309097f
};

/* Apply StandardScaler in-place to a raw feature vector */
static inline void ids_scale_features(float *x) {
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];
    }
}
