/* Auto-generated by export_firmware.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    61
#define IDS_N_FEATURES 14
#define IDS_QMAX       32767

static const int16_t ids_feature[61] = {
    5, 3, 3, 5, 5, -2, -2, 2, -2, -2, 2, 0, -2, -2, 4, -2, -2, 5, 4, 2, -2, -2, 4, -2, -2, 5, 2, -2, -2, 3, -2, -2, 4, 0, 4, 2, -2, -2, 3, -2, -2, 6, 4, -2, -2, 2, -2, -2, 3, 0, -2, 3, -2, -2, 3, 2, -2, -2, 4, -2, -2
};

static const int16_t ids_threshold[61] = {
    32703, 19591, 18451, 12529, 3534, 0, 0, 3868, 0, 0, 5988, 4096, 0, 0, 18015, 0, 0, 28591, 18015, 7906, 0, 0, 22695, 0, 0, 29747, 6920, 0, 0, 24423, 0, 0, 24060, 12288, 12889, 5797, 0, 0, 25785, 0, 0, 24203, 22695, 0, 0, 20262, 0, 0, 24652, 8192, 0, 23788, 0, 0, 26062, 19446, 0, 0, 25425, 0, 0
};

static const int16_t ids_left[61] = {
    1, 2, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1, 18, 19, 20, -1, -1, 23, -1, -1, 26, 27, -1, -1, 30, -1, -1, 33, 34, 35, 36, -1, -1, 39, -1, -1, 42, 43, -1, -1, 46, -1, -1, 49, 50, -1, 52, -1, -1, 55, 56, -1, -1, 59, -1, -1
};

static const int16_t ids_right[61] = {
    32, 17, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1, 25, 22, 21, -1, -1, 24, -1, -1, 29, 28, -1, -1, 31, -1, -1, 48, 41, 38, 37, -1, -1, 40, -1, -1, 45, 44, -1, -1, 47, -1, -1, 54, 51, -1, 53, -1, -1, 58, 57, -1, -1, 60, -1, -1
};

static const int8_t ids_leaf_class[61] = {
    -1, -1, -1, -1, -1, 1, 1, -1, 0, 1, -1, -1, 0, 0, -1, 1, 0, -1, -1, -1, 1, 0, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 0, 1, -1, -1, 0, 0, -1, 1, 0, -1, -1, 1, -1, 0, 0, -1, -1, 1, 0, -1, 0, 1
};

static const float ids_feat_min[14] = {
    -1.414214f, -2.000000f, -0.666509f, -0.820272f, -1.199466f, -0.846811f, -0.891756f, -346.408752f, -98.823296f, -135.667603f, -565.684631f, 0.000000f, 0.000000f, -0.595843f
};

static const float ids_feat_scale[14] = {
    0.000086f, 0.000076f, 0.000202f, 0.000103f, 0.000117f, 0.000077f, 0.000159f, 0.010572f, 0.017820f, 0.009744f, 0.017264f, 0.000031f, 0.000031f, 0.000201f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int16_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int16_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
